# Generated by Django 3.0.5 on 2020-04-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200401_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
